Major data update script and workflow refactoring. Customizable data updates via text files listing scripts. Renamed MASTER script to UPDATE, reflecting the new versatility. Moved most workflow logic into yml files directly. Divided data script runs for different credentials. Set workflow concurrency groups. Removed unused file-by-year breakdowns.

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -3,11 +3,17 @@ name: Routine Data Cache Request
 on:
   workflow_dispatch:
   schedule:
-    - cron: "45 8 * * *"
+    - cron: '45 8 * * *'
+
+concurrency:
+  group: data-cache
 
 defaults:
   run:
     shell: bash
+
+env:
+  TAG: CACHE
 
 jobs:
   runDataUpdate:
@@ -20,35 +26,44 @@ jobs:
       - name: Store timestamp
         run: |
           echo "TIMESTAMP=$(date -u +"%F-%H")" >> "$GITHUB_ENV"
+
       - name: Checkout
         uses: actions/checkout@v6
         with:
           path: ${{ env.REPO_DIR }}
           token: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Setup python
         uses: actions/setup-python@v6
         with:
-          python-version: "3.11"
-          cache: "pip"
-          cache-dependency-path: "${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt"
+          python-version: '3.11'
+          cache: 'pip'
+          cache-dependency-path: '${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt'
+
       - name: Install dependencies
-        run: pip install -r ${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt
-      - name: Run cache script
-        run: ./${{ env.REPO_DIR }}/.github/scripts/cache.sh
+        run: pip install -r $REPO_DIR/_visualize/scripts/requirements.txt
+
+      - name: Run data collection script
+        run: |
+          set -eu
+          cd $REPO_DIR/_visualize/scripts
+          ./UPDATE.sh $TAG
         env:
           GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Show health stats
         if: ${{ always() }}
         run: |
-          cat ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.txt || true
-          echo "Warning Count: $(grep -c 'Warning' ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.log)"
-          echo "From Timeouts: $(grep -c 'but failed' ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.log)"
-          echo "Limit Reached: $(grep -c 'rate limit exceeded' ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.log)"
+          cat $REPO_DIR/_visualize/LAST_$TAG_UPDATE.txt || true
+          echo "Warning Count: $(grep -c 'Warning' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+          echo "From Timeouts: $(grep -c 'but failed' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+          echo "Limit Reached: $(grep -c 'rate limit exceeded' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+
       - name: Save log files
         if: ${{ always() }}
         uses: actions/upload-artifact@v6
         with:
           name: logfiles_${{ env.TIMESTAMP }}_cache
           path: |
-            ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.txt
-            ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.log
+            ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.txt
+            ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.log
