Fix workflow variable usage

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -31,18 +31,18 @@ jobs:
           cache: "pip"
           cache-dependency-path: "${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt"
       - name: Install dependencies
-        run: pip install -r $REPO_DIR/_visualize/scripts/requirements.txt
+        run: pip install -r ${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt
       - name: Run cache script
-        run: ./$REPO_DIR/.github/scripts/cache.sh
+        run: ./${{ env.REPO_DIR }}/.github/scripts/cache.sh
         env:
           GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Show health stats
         if: ${{ always() }}
         run: |
-          cat $REPO_DIR/_visualize/LAST_CACHE_REQUEST.txt || true
-          echo "Warning Count: $(grep -c 'Warning' $REPO_DIR/_visualize/LAST_CACHE_REQUEST.log)"
-          echo "From Timeouts: $(grep -c 'but failed' $REPO_DIR/_visualize/LAST_CACHE_REQUEST.log)"
-          echo "Limit Reached: $(grep -c 'rate limit exceeded' $REPO_DIR/_visualize/LAST_CACHE_REQUEST.log)"
+          cat ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.txt || true
+          echo "Warning Count: $(grep -c 'Warning' ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.log)"
+          echo "From Timeouts: $(grep -c 'but failed' ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.log)"
+          echo "Limit Reached: $(grep -c 'rate limit exceeded' ${{ env.REPO_DIR }}/_visualize/LAST_CACHE_REQUEST.log)"
       - name: Save log files
         if: ${{ always() }}
         uses: actions/upload-artifact@v4
diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -31,9 +31,9 @@ jobs:
           cache: "pip"
           cache-dependency-path: "${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt"
       - name: Install dependencies
-        run: pip install -r $REPO_DIR/_visualize/scripts/requirements.txt
+        run: pip install -r ${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt
       - name: Run update script
-        run: ./$REPO_DIR/.github/scripts/update.sh
+        run: ./${{ env.REPO_DIR }}/.github/scripts/update.sh
         env:
           GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Create GitHub App Installation Token
@@ -53,7 +53,7 @@ jobs:
           git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
       - name: Commit updated data
         run: |
-          pushd $REPO_DIR
+          pushd ${{ env.REPO_DIR }}
           git stash
           git pull --ff-only
           git stash pop
@@ -64,10 +64,10 @@ jobs:
       - name: Show health stats
         if: ${{ always() }}
         run: |
-          cat $REPO_DIR/_visualize/LAST_MASTER_UPDATE.txt || true
-          echo "Warning Count: $(grep -c 'Warning' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
-          echo "From Timeouts: $(grep -c 'but failed' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
-          echo "Limit Reached: $(grep -c 'rate limit exceeded' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
+          cat ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.txt || true
+          echo "Warning Count: $(grep -c 'Warning' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
+          echo "From Timeouts: $(grep -c 'but failed' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
+          echo "Limit Reached: $(grep -c 'rate limit exceeded' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
       - name: Save log files
         if: ${{ always() }}
         uses: actions/upload-artifact@v4
