Divide data script runs for different credentials

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -13,9 +13,6 @@ defaults:
   run:
     shell: bash
 
-env:
-  TAG: FULL
-
 jobs:
   runDataUpdate:
     name: Run Data Update
@@ -45,16 +42,40 @@ jobs:
       - name: Install dependencies
         run: pip install -r $REPO_DIR/_visualize/scripts/requirements.txt
 
-      - name: Run data collection script
+      - name: Create GitHub App Installation Token1
+        uses: actions/create-github-app-token@v2
+        id: app-token1
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.PRIVATE_KEY }}
+
+      - name: Run data collection script with App Installation Token
+        run: |
+          set -eu
+          cd $REPO_DIR/_visualize/scripts
+          ./UPDATE.sh $TAG
+        env:
+          GITHUB_API_TOKEN: ${{ steps.app-token1.outputs.token }}
+          TAG: MEMBERS
+
+      - name: Validate members data updates
+        run: ./$REPO_DIR/.github/scripts/validate.sh
+        env:
+          TAG: MEMBERS
+
+      - name: Run data collection script with Action Token
         run: |
           set -eu
           cd $REPO_DIR/_visualize/scripts
           ./UPDATE.sh $TAG
         env:
           GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TAG: CORE
 
-      - name: Validate data updates
+      - name: Validate core data updates
         run: ./$REPO_DIR/.github/scripts/validate.sh
+        env:
+          TAG: CORE
 
       - name: Create GitHub App Installation Token
         uses: actions/create-github-app-token@v2
@@ -93,10 +114,12 @@ jobs:
       - name: Show health stats
         if: ${{ always() }}
         run: |
-          cat $REPO_DIR/_visualize/LAST_$TAG_UPDATE.txt || true
-          echo "Warning Count: $(grep -c 'Warning' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
-          echo "From Timeouts: $(grep -c 'but failed' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
-          echo "Limit Reached: $(grep -c 'rate limit exceeded' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+          for TAG in MEMBERS CORE; do
+            cat $REPO_DIR/_visualize/LAST_$TAG_UPDATE.txt || true
+            echo "Warning Count: $(grep -c 'Warning' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+            echo "From Timeouts: $(grep -c 'but failed' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+            echo "Limit Reached: $(grep -c 'rate limit exceeded' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+          done
 
       - name: Save log files
         if: ${{ always() }}
@@ -104,5 +127,7 @@ jobs:
         with:
           name: logfiles_${{ env.TIMESTAMP }}_update
           path: |
-            ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.txt
-            ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.log
+            ${{ env.REPO_DIR }}/_visualize/LAST_MEMBERS_UPDATE.txt
+            ${{ env.REPO_DIR }}/_visualize/LAST_MEMBERS_UPDATE.log
+            ${{ env.REPO_DIR }}/_visualize/LAST_CORE_UPDATE.txt
+            ${{ env.REPO_DIR }}/_visualize/LAST_CORE_UPDATE.log
