Rename UPDATE script, Make code more flexible/reusable

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -15,6 +15,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       REPO_DIR: main
+      TAG: FULL
       TIMESTAMP: X
     steps:
       - name: Store timestamp
@@ -71,15 +72,15 @@ jobs:
       - name: Show health stats
         if: ${{ always() }}
         run: |
-          cat ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.txt || true
-          echo "Warning Count: $(grep -c 'Warning' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
-          echo "From Timeouts: $(grep -c 'but failed' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
-          echo "Limit Reached: $(grep -c 'rate limit exceeded' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
+          cat ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.txt || true
+          echo "Warning Count: $(grep -c 'Warning' ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.log)"
+          echo "From Timeouts: $(grep -c 'but failed' ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.log)"
+          echo "Limit Reached: $(grep -c 'rate limit exceeded' ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.log)"
       - name: Save log files
         if: ${{ always() }}
         uses: actions/upload-artifact@v6
         with:
           name: logfiles_${{ env.TIMESTAMP }}_update
           path: |
-            ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.txt
-            ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log
+            ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.txt
+            ${{ env.REPO_DIR }}/_visualize/LAST_${{ env.TAG }}_UPDATE.log
