Streamlined updates with Actions and App tokens

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -4,13 +4,6 @@ on:
   schedule:
     - cron: "45 10 * * *"
 
-env:
-  # GitHub username (owner of BOT_TOKEN, will be credited for updates)
-  BOT_USER: lc-bot
-  # Paths used to store cloned repositories
-  ACTION_REPO: thisrepo
-  DATA_REPO: thisrepo
-
 defaults:
   run:
     shell: bash
@@ -20,6 +13,7 @@ jobs:
     name: Run Data Update
     runs-on: ubuntu-latest
     env:
+      REPO_DIR: main
       TIMESTAMP: X
     steps:
       - name: Store timestamp
@@ -28,32 +22,55 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          path: ${{ env.ACTION_REPO }}
-          token: ${{ secrets.BOT_TOKEN }}
+          path: ${{ env.REPO_DIR }}
+          token: ${{ secrets.GITHUB_TOKEN }}
       - name: Setup python
         uses: actions/setup-python@v5
         with:
           python-version: "3.11"
           cache: "pip"
-          cache-dependency-path: "${{ env.DATA_REPO }}/_visualize/scripts/requirements.txt"
+          cache-dependency-path: "${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt"
       - name: Install dependencies
-        run: pip install -r $DATA_REPO/_visualize/scripts/requirements.txt
+        run: pip install -r $REPO_DIR/_visualize/scripts/requirements.txt
       - name: Run update script
-        run: ./$ACTION_REPO/.github/scripts/update.sh
+        run: ./$REPO_DIR/.github/scripts/update.sh
         env:
-          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
+          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Create GitHub App Installation Token
+        uses: actions/create-github-app-token@v2
+        id: app-token
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.PRIVATE_KEY }}
+      - name: Get GitHub App User ID
+        id: get-user-id
+        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+      - name: Git config
+        run: |
+          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
+          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
+      - name: Commit updated data
+        run: |
+          git stash
+          git pull --ff-only
+          git stash pop
+          git add -A .
+          git commit -m "${{ env.TIMESTAMP }} Data Update by ${{ steps.app-token.outputs.app-slug }}"
+          git push
       - name: Show health stats
         if: ${{ always() }}
         run: |
-          cat $DATA_REPO/_visualize/LAST_MASTER_UPDATE.txt || true
-          echo "Warning Count: $(grep -c 'Warning' $DATA_REPO/_visualize/LAST_MASTER_UPDATE.log)"
-          echo "From Timeouts: $(grep -c 'but failed' $DATA_REPO/_visualize/LAST_MASTER_UPDATE.log)"
-          echo "Limit Reached: $(grep -c 'rate limit exceeded' $DATA_REPO/_visualize/LAST_MASTER_UPDATE.log)"
+          cat $REPO_DIR/_visualize/LAST_MASTER_UPDATE.txt || true
+          echo "Warning Count: $(grep -c 'Warning' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
+          echo "From Timeouts: $(grep -c 'but failed' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
+          echo "Limit Reached: $(grep -c 'rate limit exceeded' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
       - name: Save log files
         if: ${{ always() }}
         uses: actions/upload-artifact@v4
         with:
           name: logfiles_${{ env.TIMESTAMP }}_update
           path: |
-            ${{ env.DATA_REPO }}/_visualize/LAST_MASTER_UPDATE.txt
-            ${{ env.DATA_REPO }}/_visualize/LAST_MASTER_UPDATE.log
+            ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.txt
+            ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log
