Major data update script and workflow refactoring. Customizable data updates via text files listing scripts. Renamed MASTER script to UPDATE, reflecting the new versatility. Moved most workflow logic into yml files directly. Divided data script runs for different credentials. Set workflow concurrency groups. Removed unused file-by-year breakdowns.

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -3,7 +3,11 @@ name: Routine Data Update
 on:
   workflow_dispatch:
   schedule:
-    - cron: "45 10 * * *"
+    - cron: '45 10 * * *'
+
+concurrency:
+  group: data-updates
+  cancel-in-progress: true
 
 defaults:
   run:
@@ -20,35 +24,72 @@ jobs:
       - name: Store timestamp
         run: |
           echo "TIMESTAMP=$(date -u +"%F-%H")" >> "$GITHUB_ENV"
+
       - name: Checkout
         uses: actions/checkout@v6
         with:
           path: ${{ env.REPO_DIR }}
           token: ${{ secrets.GITHUB_TOKEN }}
           persist-credentials: false
+
       - name: Setup python
         uses: actions/setup-python@v6
         with:
-          python-version: "3.11"
-          cache: "pip"
-          cache-dependency-path: "${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt"
+          python-version: '3.11'
+          cache: 'pip'
+          cache-dependency-path: '${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt'
+
       - name: Install dependencies
-        run: pip install -r ${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt
-      - name: Run update script
+        run: pip install -r $REPO_DIR/_visualize/scripts/requirements.txt
+
+      - name: Create GitHub App Installation Token1
+        uses: actions/create-github-app-token@v2
+        id: app-token1
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.PRIVATE_KEY }}
+
+      - name: Run data collection script with App Installation Token
+        run: |
+          set -eu
+          cd $REPO_DIR/_visualize/scripts
+          ./UPDATE.sh $TAG
+        env:
+          GITHUB_API_TOKEN: ${{ steps.app-token1.outputs.token }}
+          TAG: MEMBERS
+
+      - name: Validate members data updates
+        run: ./$REPO_DIR/.github/scripts/validate.sh
+        env:
+          TAG: MEMBERS
+
+      - name: Run data collection script with Action Token
+        run: |
+          set -eu
+          cd $REPO_DIR/_visualize/scripts
+          ./UPDATE.sh $TAG
         env:
           GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: ./${{ env.REPO_DIR }}/.github/scripts/update.sh
+          TAG: CORE
+
+      - name: Validate core data updates
+        run: ./$REPO_DIR/.github/scripts/validate.sh
+        env:
+          TAG: CORE
+
       - name: Create GitHub App Installation Token
         uses: actions/create-github-app-token@v2
         id: app-token
         with:
           app-id: ${{ vars.APP_ID }}
           private-key: ${{ secrets.PRIVATE_KEY }}
+
       - name: Get GitHub App User ID
         id: get-user-id
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
         run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
+
       - name: Configure git
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
@@ -56,30 +97,37 @@ jobs:
           gh auth setup-git
           git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
           git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
+
       - name: Commit updated data
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
-          pushd ${{ env.REPO_DIR }}
+          set -eu
+          cd $REPO_DIR
           git stash
           git pull --ff-only
           git stash pop
           git add -A .
-          git commit -m "${{ env.TIMESTAMP }} Data Update by ${{ steps.app-token.outputs.app-slug }}"
+          git commit -m "$TIMESTAMP Data Update by ${{ steps.app-token.outputs.app-slug }}"
           git push
-          popd
+
       - name: Show health stats
         if: ${{ always() }}
         run: |
-          cat ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.txt || true
-          echo "Warning Count: $(grep -c 'Warning' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
-          echo "From Timeouts: $(grep -c 'but failed' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
-          echo "Limit Reached: $(grep -c 'rate limit exceeded' ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log)"
+          for TAG in MEMBERS CORE; do
+            cat $REPO_DIR/_visualize/LAST_$TAG_UPDATE.txt || true
+            echo "Warning Count: $(grep -c 'Warning' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+            echo "From Timeouts: $(grep -c 'but failed' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+            echo "Limit Reached: $(grep -c 'rate limit exceeded' $REPO_DIR/_visualize/LAST_$TAG_UPDATE.log)"
+          done
+
       - name: Save log files
         if: ${{ always() }}
         uses: actions/upload-artifact@v6
         with:
           name: logfiles_${{ env.TIMESTAMP }}_update
           path: |
-            ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.txt
-            ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log
+            ${{ env.REPO_DIR }}/_visualize/LAST_MEMBERS_UPDATE.txt
+            ${{ env.REPO_DIR }}/_visualize/LAST_MEMBERS_UPDATE.log
+            ${{ env.REPO_DIR }}/_visualize/LAST_CORE_UPDATE.txt
+            ${{ env.REPO_DIR }}/_visualize/LAST_CORE_UPDATE.log
